name: Comment on the pull request

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Silly workflow"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ (github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'push' }}
    outputs:
      pr_number: ${{ steps.pr_number.outputs.PR_NUMBER }}

    steps:
      - name: CMake version
        run: cmake --version
      - name: 'Download artifact'
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var fs = require('fs');
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      - run: unzip pr.zip
        if: ${{ github.event_name == 'workflow_run' }}
      - name: Save PR number
        if: ${{ github.event_name == 'workflow_run' }}
        id: pr_number
        run: echo '::set-output name=PR_NUMBER::'$(cat NR)
      - name: Send information message
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var issue_number = ${{ steps.pr_number.outputs.PR_NUMBER }};
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `The compilation is starting. Take a look [here](https://github.com/ManuelJNunez/trying/actions/runs/${context.runId}).`
            });
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'push' }}
      - name: List files
        run: ls -la

  commentpr:
    runs-on: ubuntu-latest
    needs: upload
    name: Comment PR
    if: ${{ github.event_name == 'workflow_run' }}

    steps:
      - name: 'Comment on PR'
        uses: actions/github-script@v3
        env:
          ISSUE_NUMBER: ${{ needs.upload.outputs.pr_number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var message
            if (${{ needs.build.result }} == 'success')
              message = 'Everything is OK. Thank you for the PR!'
            else
              message = 'Oops, something went wrong!'
          
            var issue_number = ${{ needs.upload.outputs.pr_number }};
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message,
            });

