name: Silly workflow

on:  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Examples build

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run the silly script
        run: python sillyscript.py
        env:
          RANDOM_VAR: ${{ secrets.RANDOM_VAR }}
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
          cp -a !(pr) pr/
      - name: Upload generated artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/

